-- PROFESSORES
INSERT INTO PROFESSOR ( CPF , NOME , SENHA, MODERADOR)
VALUES
('00011122233', 'Nome1', 'Aaaa.1234', TRUE),
('00011122234', 'Nome2', 'Aaaa.1234', FALSE);

-- DISCIPLINAS
INSERT INTO DISCIPLINA (NOME)
VALUES
('Matemática');

-- MATÉRIAS
INSERT INTO MATERIA (NOME, ID_DISCIPLINA)
VALUES
('Funções', 1),
('Funções Compostas', 1);

-- QUESTÕES
-- INSERT INTO QUESTAO
-- (ATUALIZADO_EM, CRIADO_EM, ENUNCIADO, ESPACOS, INVALIDADA, NIVEL, PUBLICA, TIPO_DE_QUESTAO, ID_AUTOR, ID_DISCIPLINA, ID_FASE_DE_ENSINO)
-- VALUES
-- (ATUALIZADO_EM, CRIADO_EM, 'Calcule x+2=3', '3', FALSE , 32.0, TRUE , , ID_AUTOR, ID_DISCIPLINA, ID_FASE_DE_ENSINO),
-- (ATUALIZADO_EM, CRIADO_EM, ENUNCIADO, ESPACOS, INVALIDADA, NIVEL, PUBLICA, TIPO_DE_QUESTAO, ID_AUTOR, ID_DISCIPLINA, ID_FASE_DE_ENSINO);